import base64url from 'base64url';

import { UNIVERSAL_WALLET_CONTEXT_URL, placeHolderImage } from '../constants';

import { getCreateOperationForProfile } from './getCreateOperationForProfile';
import { toKeyPair } from './toKeyPair';

import { DidDocument, SidetreeReplaceOptions } from '../types';
import { hashThenEncode } from './sidetreeEncoding';
import { replaceOptionsToDidCore } from './replaceOptionsToDidCore';
export const toDidDocForProfile = async (
  mnemonic: string,
  index: number,
  didMethodName: string,
  profile = 'SVIP',
  options: SidetreeReplaceOptions = {}
): Promise<DidDocument> => {
  if (profile !== 'SVIP') {
    throw new Error('SVIP Profile is only supported profile');
  }
  const signingKeyPair = await toKeyPair(mnemonic, index, 'Ed25519');
  const keyAgreementKeyPair = await toKeyPair(mnemonic, index, 'X25519');

  const createOperation = await getCreateOperationForProfile(
    mnemonic,
    index,
    profile,
    options
  );

  const didUniqueSuffix = hashThenEncode(
    base64url.toBuffer(createOperation.suffix_data)
  );
  const shortFormDid = `did:${didMethodName}:${didUniqueSuffix}`;

  const longFormDid = `${shortFormDid}?-${
    didMethodName.split(':')[0]
  }-initial-state=${createOperation.suffix_data}.${createOperation.delta}`;

  const signingKeyId = '#' + signingKeyPair.id.split('#').pop();
  const keyAgreementKeyId = '#' + keyAgreementKeyPair.id.split('#').pop();

  const didDocumentPartial = replaceOptionsToDidCore(options);

  const didDocument = {
    '@context': [
      'https://www.w3.org/ns/did/v1',
      {
        '@base': shortFormDid,
      },
    ],
    id: shortFormDid,
    publicKey: [
      {
        id: signingKeyId,
        type: 'JsonWebKey2020',
        controller: shortFormDid,
        publicKeyJwk: signingKeyPair.publicKeyJwk,
      },
      {
        id: keyAgreementKeyId,
        type: 'JsonWebKey2020',
        controller: shortFormDid,
        publicKeyJwk: keyAgreementKeyPair.publicKeyJwk,
      },
    ],
    authentication: [signingKeyId],
    assertionMethod: [signingKeyId],
    capabilityInvocation: [signingKeyId],
    capabilityDelegation: [signingKeyId],
    keyAgreement: [keyAgreementKeyId],
    ...didDocumentPartial,
  };

  return {
    '@context': [UNIVERSAL_WALLET_CONTEXT_URL],
    id: longFormDid,
    name: 'Sidetree DID',
    image: placeHolderImage,
    description: 'Generated by @sidetree/wallet.',
    tags: [],
    type: 'DID',
    didDocument,
  };
};
