import * as bip39 from 'bip39';
import hdkey from 'hdkey';
import { Ed25519KeyPair } from '@transmute/did-key-ed25519';
import {
  UNIVERSAL_WALLET_CONTEXT_URL,
  SIDETREE_BIP44_COIN_TYPE,
  placeHolderImage,
} from '../constants';

import { KeyPair } from '../types';

export const toKeyPair = async (
  mnemonic: string,
  index: number
): Promise<KeyPair> => {
  const seed = await bip39.mnemonicToSeed(mnemonic);
  const root = hdkey.fromMasterSeed(seed);
  const hdPath = `m/44'/${SIDETREE_BIP44_COIN_TYPE}'/0'/0/${index}`;
  const addrNode = root.derive(hdPath);
  const keypair = await Ed25519KeyPair.generate({
    secureRandom: () => {
      return addrNode._privateKey;
    },
  });
  return {
    ...keypair,
    '@context': [UNIVERSAL_WALLET_CONTEXT_URL],
    id: keypair.controller + keypair.id,
    name: 'Sidetree Key',
    image: placeHolderImage,
    description: 'Generated by @sidetree/wallet.',
    tags: [],
  };
};
