export const toKeyPair = async (keypair: any) => {
  return {
    '@context': [
      'https://w3c-ccg.github.io/universal-wallet-interop-spec/contexts/wallet-v1.json',
    ],
    ...keypair,
    name: 'Sidetree KeyPair',
    image:
      'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAABrUlEQVRYR+2WyYrCQBRFb5x1oQiahRMoCs6Y//8FQXFciAgKziMunI3cB4rSodtdb+qCEMp69U6dKki0arVq4h+jKQBlQBlQBpQBZeDdgN1uRzqdhs1mw3g8xm63QywWQyAQwHq9xmQy+eq1lUwm4fP5sFqtMJ1O4fF4wLHb7YbhcIjj8fha5+NlxOZerxf7/R5+vx+DwQCZTAaLxQLhcBi9Xk/++y2hUAjxeFxqdF1HvV5HPp/H/X7H5XKB2+1Gq9WyBkgkEpjNZnA6ndJ4NBrB5XKJjVwuh+12+7KQzWYFRtM0gSYcQwA2o71yuYxOp4NUKoVutyvNCVOr1awBOBoMBkEQ0zTRaDQEhvqokeRcnOF4sViUec1mU/Q+43A4pBGPlACn00nAotGobJDH8szHEXDX1H69XmEYBvr9vjRnAQvfQzOFQuEHQCQSweFwwGazeVmjIW6A6xHmPR8AJCQpd0MITqYRPjMEmc/n8lwqlbBcLkUrLxx3yvDuUDlreJnb7TYqlYqcP8O1OWZpgIMs4u/Z9KtrbzGJhs7n85/l6pNMGVAGlAFlQBl4AMRZPpDXGOp+AAAAAElFTkSuQmCC',
    description: 'Generated by @sidetree/wallet.',
    tags: [],
  };
};
