import type { NextPage } from "next";
import Head from "next/head";

import { useRouter } from "next/router";

import { AppPage } from "../../components/app-page";
import { DID } from "../../components/did";

import { RecentOperations } from "../../components/recent-operations";

import { Grid } from "@mui/material";

import { DidDocument } from "../../components/did-document";

const Resolver: NextPage = () => {
  const router = useRouter();

  const did = router.query.did as string;

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <AppPage>
          <Grid container spacing={2}>
            <Grid item xs={12}>
              <DidDocument />
            </Grid>
            <Grid item xs={12}>
              <RecentOperations />
            </Grid>
          </Grid>
        </AppPage>
      </main>
    </div>
  );
};

export default Resolver;
