name: Publish Docker image

on:
  workflow_dispatch:
  push:
    # release unstable wont run if the commit is already a stable release (tagged commit)
    tags:
      - 'v*'
      - '!v*-unstable*'
    branches:
      - main

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          context: ./packages/dashboard
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          context: ./packages/dashboard
          images: transmute/sidetree-dashboard

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./packages/dashboard
          push: true
          tags: transmute/sidetree-dashboard:latest
          labels: ${{ steps.meta.outputs.labels }}
